### PR TITLE
Recover backup

### PR DESCRIPTION
**Pull request by KatrinIhler**
This pullrequest adds a script for recovering media packages from a backup of the archive.

_This work was sponsored by SWITCH._

### CODE REVIEW

**Comment by gregorydlogan** [comment]
A quick description of what the backup format looks like would be great.  I'm *assuming* that it's expecting a raw copy of the archive tree, but someone who isn't familiar with Opencast might have a tarball (lol) or some other kind of backup format.

**Comment by KatrinIhler** [comment]
@gregorydlogan You're right about the raw copy, gonna add that to the Readme. Thanks for reviewing!

**Comment by gregorydlogan** [comment]
Providing an incorrect path generates a suboptimal error:

```./main.py -o http://localhost:8080 -u admin -p password -b /home/greg/opencast/helper-scripts/backup/
No tenant provided, using default tenant.
No mediapackages provided, recovering all.
Traceback (most recent call last):
  File "./main.py", line 75, in <module>
    main()
  File "./main.py", line 37, in main
    mps_to_recover = get_all_mediapackages(backup, tenant, lastversion)
  File "/home/greg/opencast/helper-scripts/recover-backup/script/get_mediapackages.py", line 29, in get_all_mediapackages
    dir_name, subdirs, files = next(os.walk(tenant_dir))
StopIteration```

I'm having issues testing this against develop as well, similar to #8.  Neither digest, nor normal auth seems to work

**Comment by KatrinIhler** [comment]
@gregorydlogan 
You're right, that's suboptimal, it's throwing a proper error now...

See PR #8 for testing against develop and concerning the future of the current pullrequests.

**Comment by gregorydlogan** [comment]
@KatrinIhler sounds good, will wait for the new PR(s)

**Pull request closed without merging**
