### PR TITLE
Check data integrity

### PR DESCRIPTION
**Pull request by KatrinIhler**
This pullrequest adds a script for checking the integrity of certain data in opencast.

_This work was sponsored by SWITCH._

### CODE REVIEW

**Comment by lkiesow** [comment]
I would be great if you could respect [PEP8](https://www.python.org/dev/peps/pep-0008/). For testing that + some static code analysis, I recommend [flake8](https://pypi.org/project/flake8/)

**Comment by gregorydlogan** [comment]
In a virtualenv

`python check.py` gives me this:

`Traceback (most recent call last):
  File "check.py", line 9, in <module>
    from check_data.get_assets import get_asset_of_series, get_series_of_event, get_assets_of_event, get_assets_of_oaipmh
  File "/home/greg/opencast/helper-scripts/check-data-integrity/check_data/get_assets.py", line 6, in <module>
    from check_data import create_errors
  File "/home/greg/opencast/helper-scripts/check-data-integrity/check_data/check_data.py", line 7, in <module>
    from check_data.create_errors import missing, more, asset_without_series, more_series, series_not_found, \
ImportError: No module named create_errors`

`bash check.py` works as expected?

- The readme references `main.py` rather than `check.py`
- The url, and username are listed as optional, but don't appear to be
- Testing against develop, the script never progresses past checking for tenants.  Command run `./check.py -o http://localhost:8080 -u opencast_system_account -p CHANGE_ME -c all`

**Comment by KatrinIhler** [comment]
@gregorydlogan 
I'm gonna look into the virtualenv stuff next week. In general imports are kind of a nightmare in Python, or maybe that's Pycharm's fault, I'm not sure...

Fixed the README. I couldn't find where the URL and username are listed as optional though? But it's possible I already fixed that in my local version...

Since I've moved a lot of stuff around prior to adding a new script a few days ago I'll probably create a new pullrequest with all the scripts I wrote so far and incorporating your comments (which will be quite large and terrible to review, sorry) and decline the others because that's a lot easier than fixing things in old branches and then merging that...

Testing against develop works for me if I don't include the protocol in the url (so only "localhost:8080") since whether to use http or https is set by the -s flag.

**Comment by gregorydlogan** [comment]
@KatrinIhler new PR is fine, doesn't matter to me.

Interesting.  Now plain `python` doesn't work, but `python3 check.py` does :D

Re: the optional arguments, check the output of `python3 check.py --help`.  They're **all** listed as optional!

Re: protocol, that didn't even occur to me.  Looking at the output of `--help` I would assume that it would need the protocol, but reading closer I now spot the `-l` flag.  Perhaps changing the description for `-o` to `url of the Opencast instance, without the protocol` would be clearer?

Also, now that I can test against develop I see this.  Hopefully when you look at this again it's still doing it...  Perhaps testing against develop isn't the wisest plan? :)

```
[...]
                                Starting check of OAIPMH...
                                Progress: |                                                                                                 Traceback (most recent call last):
  File "check.py", line 324, in <module>
    main()
  File "check.py", line 303, in main
    error_collector, url_builder.get_base_url(None), progress_printer)
  File "check.py", line 190, in check_oaipmh
    series_of_event, AssetType.DC, oaipmh_repo)
  File "/home/greg/opencast/helper-scripts/check-data-integrity/check_data/get_assets.py", line 146, in get_assets_of_oaipmh
    errors = check_episode_asset_of_event(episode_assets, ElementType.OAIPMH.format(repository), assettype,
AttributeError: 'Type' object has no attribute 'format'
```

**Pull request closed without merging**
